version: '3.7'
services:
  app-db:
    build: 
      context: ./Database
      dockerfile: db.dockerfile
    ports:
      - "11433:1433"
  app-server:
    build:
      context: ./ZadanieAPI
      dockerfile: api.dockerfile
    ports:
      - "3000:80"
    depends_on:
      - app-db
  app-client:
    build: 
      context: ./ZadanieClient
      dockerfile: client.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - app-server
